"""Block schema (inputs, fields, shapes, menus) for every Scratch 3 opcode and built-in extension.

``schema.json`` is generated by tools/gen_schema.py from scratch-blocks, scratch-gui's toolbox
and scratch-vm's extension definitions - it is not hand written.
"""

from __future__ import annotations

import json
from functools import lru_cache
from importlib import resources
from typing import Any


@lru_cache(maxsize=1)
def load() -> dict[str, Any]:
    return json.loads(resources.files("scratch_mcp").joinpath("schema.json").read_text(encoding="utf-8"))


def blocks() -> dict[str, dict[str, Any]]:
    return load()["blocks"]


def extensions() -> dict[str, dict[str, Any]]:
    return load()["extensions"]


def spec(opcode: str) -> dict[str, Any] | None:
    return blocks().get(opcode)


# Scratch's compressed primitive codes inside "inputs"
PRIMITIVE_CODE = {"math_number": 4, "math_positive_number": 5, "math_whole_number": 6, "math_integer": 7,
                  "math_angle": 8, "colour_picker": 9, "text": 10}
CODE_PRIMITIVE = {v: k for k, v in PRIMITIVE_CODE.items()}
BROADCAST_CODE, VARIABLE_CODE, LIST_CODE = 11, 12, 13
NUMERIC_SHADOWS = {"math_number", "math_positive_number", "math_whole_number", "math_integer", "math_angle"}

REPORTER_SHAPES = {"reporter", "boolean"}
STATEMENT_SHAPES = {"statement", "c"}
HAT_SHAPES = {"hat"}
CAP_SHAPES = {"cap"}


def opcode_catalog(category: str | None = None, query: str | None = None) -> list[dict[str, Any]]:
    """Compact listing for discovery (used by the block_manager 'catalog' action)."""
    out = []
    for op, s in blocks().items():
        if s["shape"] in ("menu", "primitive", "special") and not query:
            continue
        if category and s.get("category") != category:
            continue
        if query and query.lower() not in op.lower() and query.lower() not in str(s.get("text", "")).lower():
            continue
        ins = {n: ("boolean" if i.get("boolean") else "statement" if i["type"] == "statement" else
                   (i.get("shadow") or "any")) for n, i in s["inputs"].items()}
        out.append({"opcode": op, "category": s.get("category"), "shape": s["shape"], "inputs": ins,
                    "fields": {n: (f.get("options") or f.get("dynamic") or f["type"]) for n, f in s["fields"].items()}})
    return out
